# Generated by Django 4.2 on 2023-04-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advocate",
            name="id",
        ),
        migrations.AlterField(
            model_name="advocate",
            name="username",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
