# Generated by Django 4.2 on 2023-04-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advocate",
            name="company",
        ),
        migrations.RemoveField(
            model_name="company",
            name="name",
        ),
        migrations.RemoveField(
            model_name="company",
            name="slogan",
        ),
    ]
