# Generated by Django 4.2 on 2023-04-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_advocate_company_remove_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(default=0, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="slogan",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
