# Generated by Django 4.2 on 2023-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_advocate_company_company_name_company_slogan"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocate",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="advocate",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
